---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Always
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image }}"
          command:
            - "sh"
            - "-c"
          args:
            - "{{ .Values.command }}"
          ports:
            - containerPort: 8089
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cache-volume
              mountPath: "{{ .Values.report }}"
        - name: sidecar
          image: no8ge/sidecar:1.0.0
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - mc alias set atop http://$MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;mc mirror --remove --watch --overwrite /data atop/result/$REPORT
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: files-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: files-config
                  key: MINIO_SECRET_KEY
            - name: MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: files-config
                  key: MINIO_HOST
            - name: REPORT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: cache-volume
              mountPath: /data
      volumes:
        - name: cache-volume
          emptyDir: {}

