---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: "{{ .Release.Name }}"
spec:
  http:
    - name: {{ .Release.Name }}
      match:
        paths:
          - /plugins/{{ .Release.Name }}/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - CONNECT
          - TRACE
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /plugins/{{ .Release.Name }}/*
              - /
      websocket: true
      backends:
        - serviceName: "{{ .Release.Name }}"
          servicePort: 8089

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: "{{ .Release.Name }}"
spec:
  scheme: http
  loadbalancer:
    type: roundrobin
