---
apiVersion: v1
kind: Pod
metadata:
  name:  "{{ .Release.Name }}"
  labels:
    app:  "{{ .Chart.Name }}"
spec:
  restartPolicy: Never
  containers:
    - name: "{{ .Chart.Name }}"
      image: "{{ .Values.image }}"
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - "{{ .Values.command }}"
      ports:
        - containerPort: 7000
      volumeMounts:
        - name: cache-volume
          mountPath: "{{ .Values.report }}"
    - name: sidecar
      image: no8ge/sidecar:1.0.0
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
      args:
        - -c
        - mc alias set atop http://$MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;mc mirror --remove --watch --overwrite /data atop/result/$REPORT
      env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_ACCESS_KEY          
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_SECRET_KEY          
        - name: MINIO_HOST
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_HOST
        - name: REPORT
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: cache-volume
          mountPath: /data
  volumes:
    - name: cache-volume
      emptyDir: {}