---
apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{ .Release.Name }}-filebeat"
data:
    filebeat.yml: |
        filebeat.inputs:
        - type: filestream
          paths:
            - /var/log/hatbox/*.log
            
        output.elasticsearch:
          enabled: true
          allow_older_versions: true
          hosts: '${ELASTICSEARCH_SERVICE_HOSTS:elasticsearch-master:9200}'

