apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  restartPolicy: Never
  containers:
    - name: "{{ .Chart.Name }}"
      image: "{{ .Values.image }}"
      securityContext:
        runAsUser: 0
        privileged: false
      command:
        - "sh"
        - "-c"
      args:
        - "{{ .Values.command }}"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: report-volume
          mountPath: "{{ .Values.reports }}"
        - name: data-volume
          mountPath: /hatbox/data
        - name: log-volume
          mountPath: "{{ .Values.logs }}"
    - name: sidecar
      image: no8ge/sidecar:1.0.0
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
      args:
        - -c
        - mc alias set atop http://$MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;mc mirror --remove --watch --overwrite /data atop/result/$REPORT
      env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_ACCESS_KEY          
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_SECRET_KEY          
        - name: MINIO_HOST
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: MINIO_HOST
        - name: REPORT
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: report-volume
          mountPath: /data
    - name: filebeat
      image: docker.elastic.co/beats/filebeat:7.17.10
      ports:
        - containerPort: 5066
      args:
        - "-e"
        - "-E"
        - "http.enabled=true"
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      securityContext:
        runAsUser: 0
        privileged: false
      imagePullPolicy: IfNotPresent
      env:
        - name: ELASTICSEARCH_SERVICE_HOSTS
          valueFrom:
            configMapKeyRef:
              name: analysis-config
              key: ELASTICSEARCH_SERVICE_HOSTS
      volumeMounts:
        - name: filebeat-config
          readOnly: true
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: log-volume
          mountPath: /var/log/{{ .Chart.Name }}
  volumes:
    - name: filebeat-config
      configMap:
        name: "{{ .Release.Name }}-filebeat"
        items:
          - key: filebeat.yml
            path: filebeat.yml
    - name: data-volume
      persistentVolumeClaim:
        claimName: "data-{{ .Release.Name }}"
    - name: log-volume
      emptyDir: {}
    - name: report-volume
      emptyDir: {}