apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ .Release.Name }}"
spec:
  # storageClassName: local
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi

